SFS-Projekt-ASP.NET-Identity/Controllers/AdminController.cs
using SFS_Projekt_ASP.NET_Identity.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SFS_Projekt_ASP.NET_Identity.Controllers
{
  [Authorize(Roles = Claims.Roles.ADMIN)]
  public class AdminController : Controller
  {
    [HttpDelete]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteTask(Guid id)
    {
      BusinessLogic.BLL.Logic.DeleteTask(id);

      return RedirectToAction("RefreshTaskList", "Tasks");
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult CreateTask(string taskName)
    {
      BusinessLogic.BLL.Logic.AddTask(
        new Task()
        {
          Id = Guid.NewGuid(),
          Description = taskName,
          IsCompleted = false
        }
        );
      
      return RedirectToAction("RefreshTaskList", "Tasks");
    }
  }
}

SFS-Projekt-ASP.NET-Identity/Controllers/TasksController.cs
using SFS_Projekt_ASP.NET_Identity.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SFS_Projekt_ASP.NET_Identity.Controllers
{
  public class TasksController : Controller
  {
    [Authorize]
    public ActionResult Tasks()
    {
      IEnumerable<Task> model = BusinessLogic.BLL.Logic.GetTasks();
      
      return View(model);
    }

    [Authorize]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult AcceptTask(string id)
    {
      BusinessLogic.BLL.Logic.AcceptTask(Guid.Parse(id), User.Identity.Name);

      return RedirectToAction("RefreshTaskList");
    }

    [Authorize]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult CompleteTask(string id)
    {
      Guid idAsGuid = Guid.Parse(id);
      Task task = BusinessLogic.BLL.Logic.GetTask(idAsGuid);
      if (string.IsNullOrEmpty(task.ResponsibleUser))
      {
        ModelState.AddModelError($"Complete-{id}", "This task isn't assigned to anyone.");
      }
      if (task.ResponsibleUser != User.Identity.Name)
      {
        ModelState.AddModelError($"Complete-{id}", "You are not responsible for this task.");
      }
      if (TempData.ContainsKey("CompleteTaskErrors"))
      {
        TempData.Remove("CompleteTaskErrors");
      }
      if (ModelState.IsValid)
      {
        BusinessLogic.BLL.Logic.CompleteTask(idAsGuid);
      } else
      {
        TempData["CompleteTaskErrors"] = ModelState;
      }

      return RedirectToAction("RefreshTaskList");
    }

    [Authorize]
    public ActionResult RefreshTaskList()
    {
      if (TempData.ContainsKey("CompleteTaskErrors"))
      {
        ModelState.Merge((ModelStateDictionary)TempData["CompleteTaskErrors"]);
      }
      
      IEnumerable<Task> model = BusinessLogic.BLL.Logic.GetTasks();

      return PartialView("_TaskList", model);
    }
  }
}

SFS-Projekt-ASP.NET-Identity/Views/Tasks/Tasks.cshtml
@{
  ViewBag.Title = "Tasks";
}
@using SFS_Projekt_ASP.NET_Identity.Domain
@model IEnumerable<Task>

@{
  bool isAdmin = User.IsInRole(Claims.Roles.ADMIN);
  isAdmin = true;
}
<h1>Tasks</h1>
<div id="task-list">
    @Html.Partial("_TaskList", Model)
</div>

@if (isAdmin)
{
    <hr />
    using (Ajax.BeginForm("CreateTask", "Admin", new AjaxOptions()
    {
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "task-list"
    }))
    {
        @Html.AntiForgeryToken()
        <label>
            Description:
            <input type="text" name="taskName" required />
        </label>
        <button type="submit">Create Task</button>
    }
}

SFS-Projekt-ASP.NET-Identity/Views/Tasks/_TaskList.cshtml
@using SFS_Projekt_ASP.NET_Identity.Domain
@model IEnumerable<Task>
@{
  bool isAdmin = User.IsInRole(Claims.Roles.ADMIN);
  isAdmin = true;
}
<table class="table-condensed">
    <tr>
        <th>Description</th>
        <th>State</th>
        <th>Responsible Person</th>
        <th>Complete</th>
        @if (isAdmin)
        {
        <th>Delete</th>
        }
        <th><!-- Validation Messages --></th>
    </tr>
    @foreach (Task t in Model)
    {
    <tr>
        <td>@t.Description</td>

        <td>
            @(t.IsCompleted ? "completed" : "not completed")
        </td>

        @if (string.IsNullOrEmpty(t.ResponsibleUser))
        {
        <td>
            <div id="@t.Id">
                @using (Ajax.BeginForm("AcceptTask", "Tasks", new { id = t.Id },
                new AjaxOptions()
                {
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "task-list"
                }))
                {
                @Html.AntiForgeryToken()
                <button type="submit">Accept</button>
                }
            </div>
        </td>
        }

        @if (!string.IsNullOrEmpty(t.ResponsibleUser))
        {
        <td>
            @t.ResponsibleUser
        </td>
        }

        <td>
            @if (!t.IsCompleted)
            {
                using (Ajax.BeginForm("CompleteTask", "Tasks", new { id = t.Id },
                  new AjaxOptions()
                  {
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "task-list"
                  }))
                {
                <div>
                    @Html.AntiForgeryToken()
                    <input type="checkbox" value="Complete" name="Complete-@t.Id"
                           onchange="$('#submit-complete-@t.Id').click();" />
                    <button id="submit-complete-@t.Id" type="submit" style="display:none">Accept</button>
                </div>
                }
            }
        </td>

        @if (isAdmin)
        {
        <td>
            @using (Ajax.BeginForm("DeleteTask", "Admin", new { id = t.Id },
               new AjaxOptions()
               {
                   InsertionMode = InsertionMode.Replace,
                   UpdateTargetId = "task-list"
               }))
            {
              @Html.HttpMethodOverride(HttpVerbs.Delete)
              @Html.AntiForgeryToken()
              <button type="submit">Delete</button>
            }
        </td>
        }

        <td>
            @Html.ValidationMessage($"Complete-{t.Id}")
        </td>
    </tr>
    }
</table>